server:
  port: 19960
com:
  stalary:
    easydoc:
      path: com.stalary.easydoc
      name: Easy-Doc
      description: Easy-Doc测试项目
      contact: stalary@163.com
      open: true
      source: true
